"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = require("dotenv");
const upload_1 = __importDefault(require("./routes/upload"));
const chat_1 = __importDefault(require("./routes/chat"));
const register_1 = __importDefault(require("./routes/auth/register"));
const webRoute_1 = __importDefault(require("./routes/webRoute"));
(0, dotenv_1.config)();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: true }));
app.use('/auth', register_1.default);
app.use("/", upload_1.default);
app.use("/", webRoute_1.default);
app.use('/', chat_1.default);
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Listening on port ${port}`));
